### ISSUE TITLE
Investigate disk usage during download

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#163]
```
/srv/www/aapb/releases/20150225211146/scripts/lib/downloader.rb:55:in `write': No space left on device @ io_write - page-1029.pbcore (Errno::ENOSPC)
	from /srv/www/aapb/releases/20150225211146/scripts/lib/downloader.rb:55:in `block in download_to_directory'
	from /srv/www/aapb/releases/20150225211146/scripts/lib/downloader.rb:70:in `download'
	from /srv/www/aapb/releases/20150225211146/scripts/lib/downloader.rb:53:in `download_to_directory'
	from /srv/www/aapb/releases/20150225211146/scripts/lib/downloader.rb:38:in `download_to_directory_and_link'
	from scripts/download_clean_ingest.rb:41:in `<main>'
[deploy@rails-app1 20150225211146]$ du -s -h tmp/pbcore/
2.6G	tmp/pbcore/
[deploy@rails-app1 20150225211146]$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  3.4G  4.3G  45% /
```
(probably about half-way done.)

Did some disk GC happen after the error? Does this matter? Do we need to manage this differently?

**Comment by mccalluc** [comment]
```
Failed to add tmp/pbcore/download/2015-02-26_16:06:15_since_20000101_star
ting_page_0/page-307.pbcore: RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>10},'error'=>{'msg'=>'No space
 left on device','trace'=>'java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:345)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:395)
        at java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.apache.lucene.store.OutputStreamIndexOutput.getChecksum(OutputStreamIndexOutput.java:73)
        at org.apache.lucene.codecs.CodecUtil.writeFooter(CodecUtil.java:186)
        at org.apache.lucene.codecs.lucene49.Lucene49NormsConsumer.close(Lucene49NormsConsumer.java:178)
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:77)

Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><commit/>"

Backtrace: /home/deploy/.gem/ruby/2.1.0/gems/rsolr-1.0.10/lib/rsolr/client.rb:283:in `adapt_response'
/home/deploy/.gem/ruby/2.1.0/gems/rsolr-1.0.10/lib/rsolr/client.rb:190:in `execute'
/home/deploy/.gem/ruby/2.1.0/gems/rsolr-1.0.10/lib/rsolr/client.rb:176:in `send_an

**Comment by mccalluc** [comment]
Aha!
```
[deploy@rails-app1 20150225211146]$ df -h `pwd`
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdb       3.9G  3.7G     0 100% /srv/www

**Comment by mccalluc** [comment]
Going forward, we'll have two EBS volumes mounted, one for the data downloads, and one for the solr index. closing this.
