### ISSUE TITLE
ci.rb upload fails with larger .mp4 file (292.6 MB)

### ISSUE THREAD

**Issue by Muraszko** [WGBH/AAPB2#8]
Single .mp4 file upload via ci.rb works with 69MB and 139MB files.
Error uploading this 292.6MB file:
smb://deptfs.wgbh.org/dept/MLA/American_Archive/Sony_Ci/Test_Media/issue_8/AA_MUSIC.mp4
```
$ ruby scripts/ci/ci.rb --up /Users/michael_muraszko/Movies/AA_MUSIC.mp4 --log /Users/michael_muraszko/Desktop/TEST_LOG/log3.txt
* Adding handle: conn: 0x101880c00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x101880c00) send_pipe: 1, recv_pipe: 0
* About to connect() to api.cimediacloud.com port 443 (#0)
*   Trying 54.172.154.141...
* Connected to api.cimediacloud.com (54.172.154.141) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.cimediacloud.com
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
* Server certificate: Class 3 Public Primary Certification Authority
* Server auth using Basic with user 'michael_muraszko@wgbh.org'
> GET /oauth2/token HTTP/1.1
Authorization: Basic bWljaGFlbF9tdXJhc3prb0B3Z2JoLm9yZzoyNDI0MjRTdGFy
Host: api.cimediacloud.com
Accept: */*

< HTTP/1.1 405 Method Not Allowed
< Allow: POST
< Cache-Control: no-cache
< Content-Type: application/json; charset=utf-8
< Date: Tue, 06 Jan 2015 13:55:07 GMT
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Content-Length: 72
< Connection: keep-alive
< 
* Connection #0 to host api.cimediacloud.com left intact
* Found bundle for host api.cimediacloud.com: 0x100f69e30
* Re-using existing connection! (#0) with host api.cimediacloud.com
* Connected to api.cimediacloud.com (54.172.154.141) port 443 (#0)
* Adding handle: conn: 0x101880c00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x101880c00) send_pipe: 1, recv_pipe: 0
* Server auth using Basic with user 'michael_muraszko@wgbh.org'
> POST /oauth2/token HTTP/1.1
Authorization: Basic bWljaGFlbF9tdXJhc3prb0B3Z2JoLm9yZzoyNDI0MjRTdGFy
Host: api.cimediacloud.com
Accept: */*
Content-Length: 109
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 109 out of 109 bytes
< HTTP/1.1 401 Unauthorized
< Cache-Control: no-cache
< Content-Type: application/json; charset=utf-8
< Date: Tue, 06 Jan 2015 13:55:08 GMT
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Content-Length: 91
< Connection: keep-alive
< 
* Connection #0 to host api.cimediacloud.com left intact
* Adding handle: conn: 0x101938600
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 1 (0x101938600) send_pipe: 1, recv_pipe: 0
* About to connect() to io.cimediacloud.com port 443 (#1)
*   Trying 54.164.26.18...
* Connected to io.cimediacloud.com (54.164.26.18) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.cimediacloud.com
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
* Server certificate: Class 3 Public Primary Certification Authority
> GET /upload/multipart HTTP/1.1
Host: io.cimediacloud.com
Accept: */*
Authorization: Bearer 
Content-Type: application/json

< HTTP/1.1 405 Method Not Allowed
< Allow: POST
< Cache-Control: no-cache
< Content-Type: application/json; charset=utf-8
< Date: Tue, 06 Jan 2015 13:55:12 GMT
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Content-Length: 72
< Connection: keep-alive
< 
* Connection #1 to host io.cimediacloud.com left intact
/Users/michael_muraszko/.rvm/gems/ruby-2.0.0-p353/gems/curb-0.8.6/lib/curl/easy.rb:68: warning: uncaught exception from callback
* Found bundle for host io.cimediacloud.com: 0x100f862e0
* Re-using existing connection! (#1) with host io.cimediacloud.com
* Connected to io.cimediacloud.com (54.164.26.18) port 443 (#1)
* Adding handle: conn: 0x101938600
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 1 (0x101938600) send_pipe: 1, recv_pipe: 0
> POST /upload/multipart HTTP/1.1
Host: io.cimediacloud.com
Accept: */*
Authorization: Bearer 
Content-Type: application/json
Content-Length: 89

* upload completely sent off: 89 out of 89 bytes
< HTTP/1.1 400 Bad Request
< Cache-Control: no-cache
< Date: Tue, 06 Jan 2015 13:55:12 GMT
< Expires: -1
< Pragma: no-cache
< WWW-Authenticate: Bearer realm="Service", error="invalid_request", error_description="Missing or invalid bearer token"
< X-Frame-Options: deny
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #1 to host io.cimediacloud.com left intact
/Users/michael_muraszko/.rvm/gems/ruby-2.0.0-p353/gems/curb-0.8.6/lib/curl/easy.rb:68: warning: uncaught exception from callback
/Users/michael_muraszko/.rvm/gems/ruby-2.0.0-p353/gems/json-1.8.1/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /Users/michael_muraszko/.rvm/gems/ruby-2.0.0-p353/gems/json-1.8.1/lib/json/common.rb:155:in `new'
	from /Users/michael_muraszko/.rvm/gems/ruby-2.0.0-p353/gems/json-1.8.1/lib/json/common.rb:155:in `parse'
	from scripts/ci/ci.rb:135:in `initiate_multipart_upload'
	from scripts/ci/ci.rb:95:in `block in upload'
	from scripts/ci/ci.rb:92:in `each'
	from scripts/ci/ci.rb:92:in `upload'
	from scripts/ci/ci.rb:45:in `upload'
	from scripts/ci/ci.rb:166:in `<main>'
```

**Comment by mccalluc** [comment]
@Muraszko : I successfully uploaded the file:
```
2015-01-09 12:57:42 -0500	AA_MUSIC.mp4	866e368a969242128854a66bcf178179
```

Looking at your log (thank you for including it!) the problem seem to be that the original oath failed:
```
> POST /oauth2/token HTTP/1.1
...
< HTTP/1.1 401 Unauthorized
```

And the later actual API requests fail because the token is bad:
```
< HTTP/1.1 400 Bad Request
...
< WWW-Authenticate: Bearer realm="Service", error="invalid_request", error_description="Missing or invalid bearer token"
```

I don't know why it failed for you, but a good thing would be to fail fast if the oath handshake doesn't work out. Starting on that...

**Comment by mccalluc** [comment]
Fail-fast is implemented and tested.
